### ISSUE TITLE
MouseScroll is still active if the frame has no focus

### ISSUE THREAD

**Issue by schlubberwuz** [pampersrocker/EvoNet#15]
Hey Guys,
really nice project, i found 2 things
- Creatures went outside the generated Map
- Mousescroll is still active when the form has no focus.

**Comment by pampersrocker** [comment]
Thanks for the feedback!

Creatures are currently wip in #13 , so they are far from done.

The second is interesting because this indicates MonoGame is getting the mouse events from something else than the default Windows Message Pump, I didn't know that I need to take care of windows focus for this. I will take a look at it.

**Comment by pampersrocker** [comment]
I'm reusing this issue for the mouse scroll stuff and posted the other bug in #13 .

**Comment by Brotcrunsher** [comment]
Unfortunately, the bug is not completely fixxed yet. If Visual Studio is getting the focus, the scrolling still happens.
